import type { ScoreResult } from "../types"

export const PUZZLE_ID = "demo-142"
export const PUZZLE_NUMBER = 142
export const DATE_LABEL = "June 12, 2026"

const TARGET = "ocean"

const FIELD: Record<string, number> = {
  ocean: 1.0,
  sea: 0.84,
  water: 0.79,
  waves: 0.74,
  wave: 0.73,
  marine: 0.71,
  tide: 0.69,
  deep: 0.66,
  coast: 0.65,
  shore: 0.64,
  current: 0.63,
  coral: 0.61,
  whale: 0.6,
  salt: 0.59,
  lake: 0.58,
  dolphin: 0.575,
  seabed: 0.57,
  abyss: 0.56,
  surf: 0.55,
  beach: 0.545,
  blue: 0.54,
  fish: 0.53,
  sail: 0.52,
  ship: 0.515,
  island: 0.51,
  harbor: 0.5,
  river: 0.49,
  storm: 0.485,
  depth: 0.48,
  shark: 0.475,
  swim: 0.47,
  seaweed: 0.46,
  pacific: 0.455,
  atlantic: 0.45,
  plankton: 0.44,
  boat: 0.435,
  anchor: 0.43,
  reef: 0.425,
  jellyfish: 0.42,
  sand: 0.41,
  horizon: 0.4,
  foam: 0.39,
  vast: 0.38,
  drown: 0.37,
  pearl: 0.36,
  mermaid: 0.35,
  voyage: 0.345,
  navy: 0.34,
  liquid: 0.33,
  flood: 0.32,
  pond: 0.31,
  rain: 0.3,
  cloud: 0.27,
  sky: 0.26,
  planet: 0.25,
  earth: 0.24,
  fishing: 0.23,
  cold: 0.21,
  vacation: 0.2,
  mountain: 0.19,
  desert: 0.16,
  forest: 0.18,
  pencil: 0.05,
  keyboard: 0.04,
  banker: 0.03,
  table: 0.07,
  music: 0.09,
  happy: 0.11,
  money: 0.06,
  monday: 0.04,
  car: 0.08,
  phone: 0.06,
}

const KNOWN = new Set([
  ...Object.keys(FIELD),
  "love",
  "green",
  "red",
  "glass",
  "stone",
  "wind",
  "warm",
  "hot",
  "light",
  "dark",
  "tree",
  "grass",
  "snow",
  "ice",
  "star",
  "moon",
  "sun",
  "road",
  "city",
  "town",
  "dog",
  "cat",
  "bird",
  "game",
  "word",
  "play",
  "fast",
  "slow",
  "run",
  "jump",
  "big",
  "small",
  "tall",
  "short",
  "long",
  "wide",
  "deep",
  "high",
  "low",
  "day",
  "night",
  "morning",
  "evening",
  "year",
  "month",
  "week",
  "hour",
  "time",
  "fire",
  "air",
  "land",
  "world",
  "life",
  "death",
  "love",
  "hate",
  "fear",
  "joy",
  "food",
  "drink",
  "sleep",
  "work",
  "school",
  "home",
  "house",
  "room",
  "door",
  "window",
  "book",
  "paper",
  "pen",
  "art",
  "science",
  "math",
  "history",
  "language",
  "culture",
  "man",
  "woman",
  "child",
  "baby",
  "family",
  "friend",
  "enemy",
  "person",
  "people",
  "white",
  "black",
  "grey",
  "gray",
  "yellow",
  "orange",
  "pink",
  "purple",
  "brown",
  "north",
  "south",
  "east",
  "west",
  "sky",
  "space",
  "moon",
  "star",
  "sun",
  "planet",
  "big",
  "huge",
  "small",
  "tiny",
  "giant",
  "great",
  "good",
  "bad",
  "new",
  "old",
  "power",
  "energy",
  "force",
  "nature",
  "wild",
  "tame",
  "free",
  "open",
  "close",
  "gold",
  "silver",
  "iron",
  "stone",
  "wood",
  "metal",
  "glass",
  "plastic",
  "cloth",
  "sail",
  "wave",
  "wind",
  "flood",
  "rain",
  "snow",
  "ice",
  "frost",
  "steam",
  "fog",
  "shark",
  "whale",
  "dolphin",
  "fish",
  "crab",
  "lobster",
  "squid",
  "octopus",
  "boat",
  "ship",
  "yacht",
  "ferry",
  "submarine",
  "kayak",
  "canoe",
  "raft",
  "dive",
  "float",
  "sink",
  "swim",
  "splash",
  "ripple",
  "current",
  "stream",
  "cliff",
  "cave",
  "rock",
  "pebble",
  "shell",
  "seashell",
  "coral",
  "reef",
  "sailor",
  "pirate",
  "captain",
  "crew",
  "voyage",
  "expedition",
  "journey",
])

const rankFor = (score: number) => {
  if (score >= 0.999) return 1
  return Math.min(20_000, Math.round(Math.pow(1 - score, 2.6) * 19_998) + 2)
}

const fnv1a = (str: string) => {
  let h = 2_166_136_261
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i)
    h = Math.imul(h, 16_777_619)
  }
  return h >>> 0
}

export const scoreGuess = (word: string): ScoreResult => {
  if (!/^[a-z]{2,}$/.test(word)) return { status: "invalid" }
  if (word === TARGET) return { status: "win" }

  if (word in FIELD) {
    const score = FIELD[word]
    return { status: "scored", score, rank: rankFor(score) }
  }

  if (!KNOWN.has(word)) return { status: "unknown" }

  const score = Math.pow((fnv1a(word) % 1000) / 1000, 3) * 0.28
  return { status: "scored", score, rank: rankFor(score) }
}

export const hintAboveBest = (bestScore: number): string | null => {
  const candidates = Object.entries(FIELD)
    .filter(([, s]) => s > bestScore + 0.04 && s < 0.9)
    .sort(([, a], [, b]) => a - b)
  return candidates[0]?.[0] ?? null
}
